title = "Tdebian"
theme = "paperesque"

[[params.menu]]
  name = "evere5t"
  url = "evere5t/"

[[params.menu]]
  name = "tags"
  url = "tags/"

[[params.menu]]
  name = "denal!"
  url = "denal!/"

[[params.menu]]
  name = "t1mber"
  url = "t1mber/"
[[params.topmenu]]
  name = "t1mber"
  url = "t1mber/"

[[params.topmenu]]
  name = "denal!"
  url = "denal!/"

[[params.topmenu]]
  name = "evere5t"
  url = "evere5t/"
