apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-pvc
  namespace: hugo
spec:
  storageClassName: nfs-csi
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

