apiVersion: v1
kind: Pod
metadata:
  name: nginx-hugo
  namespace: hugo
  labels:
    app: nginx-hugo
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    - containerPort: 443
    volumeMounts:
    - name: nas-volume
      mountPath: /usr/share/nginx/html
  volumes:
    - name: nas-volume
      persistentVolumeClaim:
        claimName: nas-pvc
