apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: hugo
  labels:
    app: nginx-hugo
spec:
  type: LoadBalancer
  selector:
    app: nginx-hugo
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
