apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: hugo
  labels:
    app: nginx-hugo
spec:
  type: NodePort
  selector:
    app: nginx-hugo
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080   # <-- You can pick ports in 30000-32767
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443   # optional if you're serving HTTPS

