apiVersion: v1
kind: Pod
metadata:
  name: debug-nfs-alpine
  namespace: hugo
spec:
  containers:
  - name: debug-container
    image: alpine
    command:
      - sleep
      - "3600"
    securityContext:
      privileged: true
  restartPolicy: Never

