---
apiVersion: v1
kind: Service
metadata:
  name: fun-fact-svc
  namespace: hugo
  labels:
    app: funfact
    service: s1
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: funfact
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: funfact-serviceaccount
  namespace: hugo
  labels:
    account: funfact
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: funfact
  namespace: hugo
  labels:
    app: funfact
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funfact
      version: v1
  template:
    metadata:
      labels:
        app: funfact
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nas-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: nas-volume
          persistentVolumeClaim:
            claimName: fact-pvc

